### ISSUE TITLE
Nothing output after running a day

### ISSUE THREAD

**Issue by Renown-TAL** [novoalab/nanoRMS#10]
Hello,
I run epinano_rms.py for human sample data( 4 Gb bam file , 3 Gb reference fasta file ) , no any output or warning after running a day and I can see this progress in my server but this program with test data can finished after a minute. 
I noticed that the tmp_splitted_base_freq dir remain small_*.freq file and CHUNK_*.txt which number of CHUNK_*.txt is lastest  small_*.freq +1. Beside , the number of files in tmp_splitted_base_freq dir change when I try again. 
I guess something break in the  program but I can't find why because no any warning. Could you give me some help?
Thanks a lot for your help in advance.

**Comment by Huanle** [comment]
Hi @Renown-TAL ,

I do not know what happened.
But can you try splitting your bam into small files and try this script on a few of them to see if it works?
you can split your bam file through:
`samtools view -hb big.bam chromosome_id > reference_sequence_id.bam`
