### ISSUE TITLE
About mkae a RNA_Mod_Positions file

### ISSUE THREAD

**Issue by Renown-TAL** [novoalab/nanoRMS#11]
Hello,
I tried nanoRMS for human sample, so I need to make a RNA_Mod_Positions file for human, but I have two question as folloing:

1. Could you provide a list for what the modification abbreviation mean like the mod column in  the RNA_Mod_Positions_rRNAYeast.tsv?
I am not sure I can write modification as same as your mean.
2. Is necessary to provide all type of modification for each site? 
For example, I provide the site of pseudouridine or site of pseudouridine and m6A, will the second one get a better result?

Thanks a lot for you in advance.

**Comment by enovoa** [comment]
Hi @Renown-TAL, I am not sure in which step/command you are using this file. Can you pls clarify? Thx!

**Comment by Renown-TAL** [comment]
Hi,
This step is&nbsp;1.2. Predict RNA modifications,(a)&nbsp;Single sample RNA modification prediction&nbsp;(i.e. "de novo" prediction). The&nbsp;default input file of parameter -p&nbsp;mod positions file&nbsp;is "positions/RNA_Mod_Positions_rRNAYeast.tsv".








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "novoalab/nanoRMS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月22日(星期二) 下午5:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [novoalab/nanoRMS] About mkae a RNA_Mod_Positions file (#11)





 
Hi @Renown-TAL, I am not sure in which step/command you are using this file. Can you pls clarify? Thx!

**Comment by Renown-TAL** [comment]
I read your paper carefully and get all the abbreviation , thanks.

**Comment by enovoa** [comment]
thanks - i understand then that your question is solved, so i will close the issue.
