### ISSUE TITLE
code in get_features.py

### ISSUE THREAD

**Issue by zhongzhendong** [novoalab/nanoRMS#13]
Hi!
Maybe the order of op_len and op is reverse in the 109 line?
And the a.alen in the 107 line should be the sum of the num_match, num_mismatch and num_del, rather than the number of the num_match?
![image](https://user-images.githubusercontent.com/57746970/125151179-db356700-e177-11eb-9d0c-9dc2583c5124.png)

**Comment by zhongzhendong** [comment]
and the a.alen should be the sum of the num_match, num_mismatch and num_del, rather than the number of the num_match?
![image](https://user-images.githubusercontent.com/57746970/125151089-3a46ac00-e177-11eb-97cd-7cd7989ac45e.png)

**Comment by lpryszcz** [comment]
Hi @zhongzhendong , you're right, there was a mistake. 
Anyway, those metrics were redundant, so I've just remove it from the code. 
Cheers!
