### ISSUE TITLE
Error occured durin epinano_rms.py  command

### ISSUE THREAD

**Issue by aman21392** [novoalab/nanoRMS#15]
I used below command:-
nohup python3 /home/apps/nanoRMS/epinano_RMS/epinano_rms.py -R /Drive7/circ_nanopore_modification_analysis/NanoRMS/control/Homo_cdna.fa -b /Drive7/circ_nanopore_modification_analysis/NanoRMS/control/control_fullrepli.bam -s /home/apps/nanoRMS/epinano_RMS/sam2tsv.jar &

It gives the following errors:-

bam file not indexed!
starting indexing it
...Traceback (most recent call last):
  File "/home/aclab/apps/nanoRMS/epinano_RMS/epinano_rms.py", line 354, in <module>
    main()
  File "/home/aclab/apps/nanoRMS/epinano_RMS/epinano_rms.py", line 319, in main
    touch (".{}.done_splitting".format(tmp_dir))
  File "/home/aclab/apps/nanoRMS/epinano_RMS/epinano_rms.py", line 25, in touch
    open(fname, 'a').close()
FileNotFoundError: [Errno 2] No such file or directory: './Drive7/circ_nanopore_modification_analysis/NanoRMS/control/control_fullrepli.tmp

Please sort out this issue. Thanks in advance

**Comment by enovoa** [comment]
I assume this has been solved. If it hasn't, please re-open the issue. Thanks!
