### ISSUE TITLE
psU Prediction 

### ISSUE THREAD

**Issue by AminaLEM** [novoalab/nanoRMS#16]
Hello, 

I want to predict psU modifications in my data using nanoRMS ... To do so, I realized that I need a file containing the modified positions ? I am a bit confused since this is what I am looking for ... which positions are modified, is the prediction without this information reliable ?

Best regards, 

Amina

**Comment by obegik** [comment]
Hi,

You don't necessarily need to have a list of these positions. What you need is that table though. You can use the example table without any positions (just keeping the header). This should work.

Thanks,

Oguzhan

**Comment by AminaLEM** [comment]
Hi @obegik  

Alright. Thank you for the quick reply.

Best regards, 

Amina

**Comment by enovoa** [comment]
Hi @AminaLEM , i'd like to note that you should ideally obtain a filtered list of psU candidates using the first steps described in the repository  - please see section 1. Prediction of RNA modified sites  (https://github.com/novoalab/nanoRMS/blob/master/README.md#1-prediction-of-rna-modified-sites).

**Comment by wvdtoorn** [comment]
Hi @obegik 

> You can use the example table without any positions (just keeping the header). This should work.

Which example table do you mean here?

Thanks and cheers,
Wiep

**Comment by AminaLEM** [comment]
> Hi @obegik
> 
> > You can use the example table without any positions (just keeping the header). This should work.
> 
> Which example table do you mean here?
> 
> Thanks and cheers, Wiep

**Comment by enovoa** [comment]
Hello, is this issue solved? thanks, Eva
