### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by yuxinPenny** [novoalab/nanoRMS#22]
I came up with the flowing error while running the epinano_rms script. However, I do not know why the tmp_splitted_base_freq.done splitting file can not be found. Can you give some clues?

Traceback (most recent call last):
  File "/home/share/yuxin/nanoRMS/epinano_RMS/epinano_rms.py", line 354, in <module>
    main()
  File "/home/share/yuxin/nanoRMS/epinano_RMS/epinano_rms.py", line 319, in main
    touch (".{}.done_splitting".format(tmp_dir))
  File "/home/share/yuxin/nanoRMS/epinano_RMS/epinano_rms.py", line 25, in touch
    open(fname, 'a').close()
FileNotFoundError: [Errno 2] No such file or directory: './home/share/yuxin/2021Fall/DATA/hm_tmp/HMEC_WT/bam/HMEC_WT_g.tmp_splitted_base_freq.done_splitting'

P.S. commands to run:
python3 /home/share/yuxin/nanoRMS/epinano_RMS/epinano_rms.py \
-R /home/share/yuxin/2021Fall/DATA/hm_tmp/hg38.fa \
-b /home/share/yuxin/2021Fall/DATA/hm_tmp/HMEC_WT/bam/HMEC_WT_g.bam \
-s /home/share/yuxin/nanoRMS/epinano_RMS/sam2tsv.jar -d -n 10

**Comment by Huanle** [comment]
Hi @yuxinPenny ,

Thanks for using `epinano_rms.py`, can you try calling the program from the folder where you have your bam files stored?
I believe it will work.

That said, I also attached a modified version of the script, which is supposed to overcome that error you ran into.So, can you try it out and let me know if it works?
[epinano_rms.py.txt](https://github.com/novoalab/nanoRMS/files/7528486/epinano_rms.py.txt)

**Comment by enovoa** [comment]
I assume this has been solved so closing this issue. If it hasn't, please re-open. Thanks!
