### ISSUE TITLE
Object mask error

### ISSUE THREAD

**Issue by yuxinPenny** [novoalab/nanoRMS#23]
When I run the /home/share/yuxin/nanoRMS/predict_rna_mod/Pseudou_prediction_singlecondition.R script, It returns the following. In addition an empty Sample1_predicted_y_sites.tsv returned. Can you give some clues?

Attaching package: ‘dplyr’

The following objects are masked from ‘package:plyr’:

    arrange, count, desc, failwith, id, mutate, rename, summarise,
    summarize

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Loading required package: grid
Loading required package: futile.logger

Attaching package: ‘data.table’

The following objects are masked from ‘package:dplyr’:

    between, first, last

PS. the command to run:
Rscript --vanilla /home/share/yuxin/nanoRMS/predict_rna_mod/Pseudou_prediction_singlecondition.R \
-f /home/share/yuxin/2021Fall/DATA/hm_tmp/HMEC_WT/bam/HMEC_WT_g.per.site.baseFreq.csv \
-p /home/share/yuxin/nanoRMS/predict_rna_mod/positions/RNA_Mod_Positions_rRNAYeast.tsv

**Comment by obegik** [comment]
Hi,

The messages are okay. They are not related to any problem. The fact that it's giving an empty table might mean that there is not any pseudouridine position that could be predicted. Is this an mRNA run ?

**Comment by yuxinPenny** [comment]
Thanks, this is an mRNA run. However, after changing the Position to mRNA_mod positions, it returned this error:

Error in fix.by(by.y, y) : 'by' must specify a uniquely valid column

**Comment by yuxinPenny** [comment]
It seems that the script can only work with the /positions/RNA_Mod_Positions_rRNAYeast.tsv file

**Comment by obegik** [comment]
Yes because that script is written to investigate the rRNA reads. For the mRNA, we only have the script that works for pairwise conditions : WT/KO, Normal/Heat-shock etc.
