### ISSUE TITLE
ValueError: Columns must be same length as key

### ISSUE THREAD

**Issue by ssscj** [novoalab/nanoRMS#24]
Hi,
thanks for developing this software, I encountered some problems while testing it on the given test dataset during the step1 epinano_rms.py
1. FileNotFoundError: [Errno 2] No such file or directory: , so I delete the a dot in touch (".{}.done_splitting".format(tmp_dir)) to touch ("{}.done_splitting".format(tmp_dir)),  and it worked.
2.  line 93, in proc_small_freq
    df[['_A_', '_C_', '_G_', '_T_']] = df['bases'].str.split(pat=':',  expand=True)
  File "envs/nanoRMS6/lib/python3.6/site-packages/pandas/core/frame.py", line 3041, in __setitem__
    self._setitem_array(key, value)
  File "/envs/nanoRMS6/lib/python3.6/site-packages/pandas/core/frame.py", line 3067, in _setitem_array
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key

thanks in advance.

Chujie

**Comment by enovoa** [comment]
HI @ssscj, Please provide example on how you executed the command, exact command error output, and data to reproduce the error. Based on the information above,  it seems that you are not providing a file that exists, or the path is not the correct one.

**Comment by ssscj** [comment]
Sorry for the confusion, there were two errors when I ran the epinano_rms.py. The command is :
`python ~/software/nanoRMS/epinano_RMS/epinano_rms.py -R nanoRMS/predict_rna_mod/references/yeast_all_rRNA.fa -b  nanoRMS/predict_rna_mod/test_data/test.bam -s nanoRMS/epinano_RMS/sam2tsv.jar`
1. the first error I met is:
`Traceback (most recent call last):`
 ` File "nanoRMS/epinano_RMS/epinano_rms.py", line 354, in <module>
    main()`
`  File "nanoRMS/epinano_RMS/epinano_rms.py", line 319, in main
    touch (".{}.done_splitting".format(tmp_dir))`
  `File "nanoRMS/epinano_RMS/epinano_rms.py", line 25, in touch
    open(fname, 'a').close()`
`FileNotFoundError: [Errno 2] No such file or directory: './path/test.tmp_splitted_base_freq.done_splitting'`
so I check the code in epinano_rms.py, and found that in the line 319 `touch (".{}.done_splitting".format(tmp_dir))`, a `.` is in front of `{}`, if the bam file is not in the subdirectory of the working directory, the error will be raised, so I delete the `.`
2. the second error I met is:
`nanoRMS/predict_rna_mod/test_data/test.tmp_splitted_base_freq already exists, will overwrite it`
`Traceback (most recent call last):`
`  File "nanoRMS/epinano_RMS/epinano_rms.py", line 354, in <module>`
   ` main()`
 ` File "nanoRMS/epinano_RMS/epinano_rms.py", line 326, in main`
   ` df = proc_small_freq (f)`
 ` File "nanoRMS/epinano_RMS/epinano_rms.py", line 93, in proc_small_freq`
   ` df[['_A_', '_C_', '_G_', '_T_']] = df['bases'].str.split(pat=':',  expand=True)`
 ` File "nanoRMS6/lib/python3.6/site-packages/pandas/core/frame.py", line 3041, in __setitem__`
  `  self._setitem_array(key, value)`
  `File "nanoRMS6/lib/python3.6/site-packages/pandas/core/frame.py", line 3067, in _setitem_array`
  `  raise ValueError("Columns must be same length as key")`
`ValueError: Columns must be same length as key`

thanks

**Comment by ssscj** [comment]
Hi,
I found that this problem is caused by my environment. In my environment for nanoRMS, the samtools was disabled. Thanks for your help!

**Comment by sdietmann** [comment]
Hi,
I have the same issue, but samtools is available in my environment. Thanks for your help with this. !

Traceback (most recent call last):

  File "nanorms.analysis/nanorms/epinano_RMS/epinano_rms.py", line 326, in main
    df = proc_small_freq (f)
  File "nanorms.analysis/nanorms/epinano_RMS/epinano_rms.py", line 93, in proc_small_freq
    df[['_A_', '_C_', '_G_', '_T_']] = df['bases'].str.split(pat=':',  expand=True)
  File "miniconda3/envs/nanopore/lib/python3.9/site-packages/pandas/core/frame.py", line 3643, in __setitem__
    self._setitem_array(key, value)
  File "miniconda3/envs/nanopore/lib/python3.9/site-packages/pandas/core/frame.py", line 3685, in _setitem_array
    check_key_length(self.columns, key, value)
  File "miniconda3/envs/nanopore/lib/python3.9/site-packages/pandas/core/indexers/utils.py", line 428, in check_key_length
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key

**Comment by enovoa** [comment]
Hi, can you please try running with the test data? I assume that it is a problem related to your environment. https://github.com/novoalab/nanoRMS/tree/master/predict_rna_mod/test_data 
Thanks
Eva

**Comment by sdietmann** [comment]
Hi Eva, thank you for your prompt response. The test data worked ! I have mapped my data with minimap2, and your test data is mapped by graphmap. Does nanoRMS need a specific field or very specific sorting?

**Comment by enovoa** [comment]
Hi @sdietmann i dont think it has to do with the mapping algorithm, because we have used this code with data mapped with graphmap as well as minimap. NanoRMS does not require any specific field or sorting. My guess is that there is some issue with your specific BAM file. Sorry I can't be of more help. Please note that the EpiNano_RMS script must be executed from wherever the bam file is (i.e. don't do ../myfile.bam when passing it as variable), we realized this was an issue and hasn't yet been corrected for. Hope that helps!
