### ISSUE TITLE
Error in Running Epinano-RMS

### ISSUE THREAD

**Issue by septav** [novoalab/nanoRMS#25]
Hi. 
Thanks for developing this software.
 I was able to run epinano_rms.py for one of my bam files without any error. However, when I tried the same steps for another bam file I got these issue that I am not sure how to solve. 
 <img width="1069" alt="Screen Shot 2022-01-06 at 11 34 26 AM" src="https://user-images.githubusercontent.com/71278338/148416908-f3b1d8b6-3a18-420e-b3af-3fd42dbd4412.png">
Thanks for your help in advance.

**Comment by Huanle** [comment]
Hi @septav ,

Sorry for the late response. Can you quicly chekc sam2tsv.jar on your bam file and see whether it outputs anything?

**Comment by enovoa** [comment]
I assume this has been solved, so closing this issue. If it hasnt please re-open. Thanks!
