### ISSUE TITLE
Create sequence dictionary

### ISSUE THREAD

**Issue by nagarkarsanket** [novoalab/nanoRMS#26]
Hello,
While the previous issue with the typeError got sorted for me, the following started coming up-

"yeast_ref.dict.dict needs to be created using picard.jar CreateSequenceDictionary"

This comes up even though I have created the sequence dictionary with picard.

**Comment by obegik** [comment]
Hi,

You need to rename the yeast_ref.dict.dict to yeast_ref.dict.
