### ISSUE TITLE
what are the meaning of Guppy output fast5 files's trace and move dataset? 

### ISSUE THREAD

**Issue by Cynthia0411** [novoalab/nanoRMS#28]
I tried to read the get_feature.py file and found the trace feature was extracted with the move dataset. So I tried to do guppy basecall as the paper indicated and see a trace and move dataset in the output fast5 files. However, I am not sure how to interpret these two dataset. How can I translate the move and trace dataset into the basecall result contained in the fastq file?

**Comment by enovoa** [comment]
Hi @Cynthia0411 , thanks for your message. I am sorry but NanoRMS does not translate move and trace datasets into the fastq files.
