### ISSUE TITLE
per_read/get_freq.py:  The error message says "[ERROR] -m/--mincov must be at least 5!", but the check is for at least 10.

### ISSUE THREAD

**Issue by mnrusimh** [novoalab/nanoRMS#29]
On line 87, it should have been

`if o.mincov<5:`

Also, the help description for mincov could be corrected too.

**Comment by lpryszcz** [comment]
Hi, it's exactly as you commented in the source
https://github.com/novoalab/nanoRMS/blob/master/per_read/get_freq.py#L87
