### ISSUE TITLE
Problem with epinano_rms.py

### ISSUE THREAD

**Issue by twocata** [novoalab/nanoRMS#30]
Hi,
this is my first time using nanoRMS, and I had a problem running the following command:
python3 epinano_rms.py -R ../RNA_ref.fa -b ../poke.sorted.bam -s ./epinano_RMS/sam2tsv.jar
The result is as follows:
Traceback (most recent call last):
  File "epinano_rms.py", line 354, in <module>
    main()
  File "epinano_rms.py", line 319, in main
    touch (".{}.done_splitting".format(tmp_dir))
  File "epinano_rms.py", line 25, in touch
    open(fname, 'a').close()
FileNotFoundError: [Errno 2] No such file or directory: 
'.../poke.sorted.tmp_splitted_base_freq.done_splitting'

How can I solve this problem?
Thank you in advance.

**Comment by AnWiercze** [comment]
Hi, I had the same problem and found an "closed issue" regarding this "bug". You need to run the command from the same folder where your bam file is located. Hope this helps!
