### ISSUE TITLE
modpos file missing 

### ISSUE THREAD

**Issue by Tanujgn** [novoalab/nanoRMS#32]
Hi
I have generated epinano files for 2 samples and I want to run Pseudou_pairedcondition_transcript.R for prediction of RNA modifications among my two epinano output csv files. But I encounter error of modified positions file (modpos) not found. How can I generate this modpos file.

Best regards

**Comment by enovoa** [comment]
Hi @Tanujgn - Can you please include commands used so far, I can't understand what you are trying to do from the epinano output files? Thanks!

**Comment by Tanujgn** [comment]
Sorry for the lack of clarity
I was referring to the output files of epinano_RMS from 1.1 section. I generated csv files from epinano_RMS and want to give these as input files for 1.2 section where in I'm facing error of positions file not found.
Can you tell how to generate pU modification position file for human genome just like the yeast_all_modifications.tsv file which is being used as default for 1.2 section Rscripts

**Comment by enovoa** [comment]
Hi @Tanujgn
You need to build your own modpos tsv file with known pseduoU modifications from whatever public databases are available for your species of interest. There are several available resources for human pseudoU modifications, e.g. https://pubmed.ncbi.nlm.nih.gov/30202881/ 
You can manually build your own modpos file from these and other resources, as we did for the yeast, based on publicly available resources like the one mentioned above. 
Best, Eva

**Comment by Tanujgn** [comment]
I will try that.
Thank you

**Comment by Tanujgn** [comment]
We  came across the list of pseudoU modifications (screenshot_mentioned below). 
![Human psu sites](https://user-images.githubusercontent.com/74550008/203614134-d1b57401-d06a-48fd-b104-0feb339dca79.JPG)

We dont have chromsome, genome location and strand details like the modpos file mentioned in your script. Do we need to add chromosome, genome location and strand details like the yeast_modpos file (screenshot mentioned below) or can we proceed without them?

![modpos file in nanoRMS](https://user-images.githubusercontent.com/74550008/203610539-a8934186-511e-4e65-a899-b9e5f227388e.JPG)

**Comment by obegik** [comment]
Hi Tanujgn,

In order to determine the pU sites, you need to feed the script with  chromosome, genome location and strand  information.
