### ISSUE TITLE
modpos

### ISSUE THREAD

**Issue by vetmohit89** [novoalab/nanoRMS#33]
I am having a similar question as GN Tanuj asked earlier. Why do we need the modpos (**nanoRMS/predict_rna_mod/positions**) file to run the Pseudou_pairedcondition_transcript.R script for the prediction of RNA modifications using our two epinano output CSV files? We are working with human PUS7 knockdown vs wildtype samples but I do not find any publication showing specifically PUS7 mRNA targets in the human transcriptome. What should I do in that case? How can I find PUS7 target mRNA in my samples in the absence of previously identified PUS7 targets in human transcriptome?

**Comment by obegik** [comment]
Hi,

You can simply use an empty table (keeping the header information). The script should shill run.

**Comment by ssscj** [comment]
hi, I used an empty table with the header information, the script run successfully, but the output was also empty.

**Comment by obegik** [comment]
Hi,

This simply means you don't have any significant sites.

**Comment by enovoa** [comment]
HI @ssscj  -- Please note that the settings used by this code were largely benchmarked using pseudoU modifications in rRNA, which are high stoichiometry. You may wish to consider tweaking the parameters used in the script to define lower thresholds. Also I'd like to note that in our previous experiences, the use of knockdowns for studying RNA modification changes is rather bad, the differences between conditions are too small -- using KOs makes the analysis much cleaner.   Best, Eva

**Comment by ssscj** [comment]
> 

Hi,
Thanks for your reply. I checked the code and this line `merge(final, mod_file, by.x=c("Chr", "Pos"), by.y=c("Chr", "Position"))` might cause the empty output. Thanks.

**Comment by ssscj** [comment]
@enovoa  thank you, I will try different parameters and check the results.

**Comment by enovoa** [comment]
Have you tried using the demo data following what is shown in the README?
