### ISSUE TITLE
Epinano-RMS

### ISSUE THREAD

**Issue by vetmohit89** [novoalab/nanoRMS#35]
EpinanoRMS script shows the message "KILLED" after it's done. I am just confirming here that this message shows the completion of the job or it is because of any error Please see attached image. ![epinanoRMS output](https://user-images.githubusercontent.com/110649675/204660787-98934aeb-347b-4ef4-baba-642e50449aa0.JPG)

**Comment by enovoa** [comment]
Hi @vetmohit89  - I assume you ran out of resources. You may want to submit this to a node with more resources? Have you tried the demo example? Thanks
