### ISSUE TITLE
CSV file for human transcriptome

### ISSUE THREAD

**Issue by vetmohit89** [novoalab/nanoRMS#36]
I am trying to run the _epinan0_rms.py script_ for analyzing human transcriptome data. I have generated the bam files as per the instructions. I found every time **out of memory error** when I ran the above _script._ 

As per the latest discussion, I re-ran the script with 1TB of total mem and it still failed. I am not sure what is going on and how to fix it. But upon checking the errors in google, I believe it is something to do with the iteritems in the script. I am attaching the error file I got after running the script. Please see what I am missing here. 
![image](https://user-images.githubusercontent.com/110649675/205160371-1b28db13-9f33-4f4a-9ed0-1dfe836ac373.png)
me in fixing this issue. 

Do you think I should do mapping with fewer fastq files followed by epinan0_rms.py script and later, merge all the CSV files of individual samples to obtain the final CSV file?

**Comment by enovoa** [comment]
Hi @vetmohit89, We did not test epinano_RMS on human transcriptome, only on yeast. Can you please try the script with the yeast transcriptome-wide data accompanying the Nat Biotech manuscript (publicly available in ENA)? Alternatively, following your own suggestion, you may wish to split by chromosome (but not fewer fastq as afterwards it will be complex to merge the CSV files).

**Comment by vetmohit89** [comment]
So, I should map all the fastq files using references for each chromosome file?
