### ISSUE TITLE
Ouput from Pseudou_prediction_pairedcondition_transcript.R

### ISSUE THREAD

**Issue by vetmohit89** [novoalab/nanoRMS#37]
I tested the script Pseudou_prediction_pairedcondition_transcript using your test WT_ncRNA_Normal_Rep1_Epinano.csv and WT_ncRNA_HeatShock_Rep1_Epinano.csv found no difference. Howver, you have shown some of the locations has pseudourdine modification. 

I used following commands (attached image).
![pseudoU prediction script](https://user-images.githubusercontent.com/110649675/212544311-d2e5050a-e853-4680-af9a-1e837b251bfd.jpg)

Please see comparision of my output  (left) and yours (right) from Pseudou_prediction_pairedcondition_transcript script from the same input data in the screenshot. Numbers in all the rows are similar but I do not see "YES" in my output.
![Pseudou_prediction_pairedcondition_transcript R results](https://user-images.githubusercontent.com/110649675/212544316-4253ffa9-950b-43da-9cfd-34bc8b997046.jpg)

Thank you,
Mohit

**Comment by vetmohit89** [comment]
I have used following modpos file for running the script. 
![modpos](https://user-images.githubusercontent.com/110649675/212755531-46832081-3059-4fe0-a4db-f98195095ca8.jpg)

**Comment by obegik** [comment]
HI Mohit,

Did you actually use the same modpos file that we use for test? Because it seems like it's just a matter of how you classified your positions in the modpos file that is different. 

Oguzhan

**Comment by vetmohit89** [comment]
Hello Oguzhan,
Thank you so much for prompt reply.
As you suggested, I have tried with RNA_Mod_Position_ncRNAYeast_HeatSensitive.tsv this time and it works fine. But, I tried to use same modpos file keeping only the header for my csv files comparision then it did not work. I am wondering how to run this R script in the absence of modpos file and can we have a universal modpos file empty template for comparing csv file? Because, I see more than 70% pseudouridylation when comparing bam files in IGV but this script is not showing that.

**Comment by obegik** [comment]
Dear Mohit,

The reason it says "No" for the pseudouridine column is because this position was not originally in the modes file as previously annotated position. So, the fact that you are getting this position in the output actually already means that you have a pseudouridine-like position.

Best,
Oguzhan

Closing this issue now
