### ISSUE TITLE
How to make files like RNA_Mod_Positions_rRNAYeast.tsv in other species

### ISSUE THREAD

**Issue by ShelaLJJ** [novoalab/nanoRMS#38]
Hello, thank you for making this software.

I notice that prediction of RNA modifications (section 1.2) use [Pseudou_prediction_singlecondition.R] file or [Pseudou_prediction_pairedcondition_transcript.R] file, which employs "predict_rna_mod/positions/RNA_Mod_Positions_rRNAYeast.tsv" as the mod position file. May I ask how this "RNA_Mod_Positions_rRNAYeast.tsv" file is made? If I want to use nanoRMS on human mRNA to predict pseudouridine modification, how to make a similar file like "RNA_Mod_Positions_rRNAYeast.tsv" ?

**Comment by obegik** [comment]
Hi Shela,

You can simply take the example file and edit it according to your "Known" sites. Or you can leave it empty in case you don't have any previous knowledge about the sites.

Best,
Oguzhan

**Comment by ShelaLJJ** [comment]
Thanks a lot for your prompt reply, Oguzhan! I will have a try.
