### ISSUE TITLE
mod file missing from Pseudou_prediction_singlecondition.R

### ISSUE THREAD

**Issue by eoziolor** [novoalab/nanoRMS#5]
Hi, I am trying to use Pseudou_prediction_singlecondition.R to predict modified sites, but I am running into an issue of missing "mod" file that is not described in the README and is not present in the github files. Would you be able to point me to a description of this mod file or an example?

**Comment by eoziolor** [comment]
In addition, the "example" script for using Pseudou_prediction_singlecondition.R, has the wrong R file name (I am guessing a former naming of the same script)

**Comment by obegik** [comment]
Hi Elias, 

Mod file should be the "RNA_Mod_Positions_rRNAYeast.tsv" file, located on positions folder. This file contains "known" Y sites. By default, it uses the file located in the positions folder.

 I fixed the script name on the README file.  Please note that I am still updating some scripts. So in case you need help with a specific script, I would be happy to help faster.

Best,
Oguzhan

**Comment by eoziolor** [comment]
Thanks @obegik! Where would I find the "positions" folder? I haven't been able to see it in this repo and I don't think it was generated in any of the previous steps.

Thanks for your help!

-Elias

**Comment by eoziolor** [comment]
Ha! Never-mind I found it under "Part1"! Thank you!
