### ISSUE TITLE
Extra period in .{}.done_splitting?

### ISSUE THREAD

**Issue by eoziolor** [novoalab/nanoRMS#6]
Don't know if this is just my environment, but to run epinano_rms.py, I had to remove the extra initial period from

".{}.done_splitting".format(tmp_dir)

The script ran fine when I did this, so just checking wanted to put this out here.

**Comment by 690645258** [comment]
I had the same issue. Running it with your bams in the nanoRMS directory also works but isn't the cleanest.

**Comment by Huanle** [comment]
Hi @eoziolor @690645258 ,
it is a hidden file generated when the specific step was successfully completed -- the splitting reads step, the one creating the tmp folder, to be specific.  so if re-analysis is needed, the script will detect the hidden file and skip this step. you can switch on the argument to remove the folder in the relevant python script. 

Did you manually delete the tmp folder but did not remove the hidden file, can you check with `ls -la`?

**Comment by AminaLEM** [comment]
It doesn't work for me as well, I don't see where it is created in the code !

**Comment by Huanle** [comment]
Hi @AminaLEM ,

Can you replace it with the script I attached and let me know if it works or not?
Thanks. 

PS: Please change its name by removing `.txt`. 

[epinano_rms.py.txt](https://github.com/novoalab/nanoRMS/files/6502075/epinano_rms.py.txt)

**Comment by AminaLEM** [comment]
Hi @Huanle ,

Thank you for your prompt reply, yes it works now.
