### ISSUE TITLE
get_features.py: cannot convert float NAN to integer

### ISSUE THREAD

**Issue by hanliaoucla** [novoalab/nanoRMS#7]
I came across a problem with get_features.py:

When I test the get_features.py with testing data (yeast date as described in readme), the console showed:
....
4000 - 3999 read skipped: {'cannot convert float NAN to integer': 3588 'No alignment': 411}
....
Anyone has some suggestions to solve this problem?

Thanks in advance!

**Comment by lpryszcz** [comment]
This is related to [tombo issue with numpy v1.20 or newer](https://github.com/nanoporetech/tombo/issues/319). Please downgrade your numpy version. 

```bash
pip install "numpy<1.20"
```

This information is now added to [dependencies](https://github.com/novoalab/nanoRMS#dependencies-and-versions).
