### ISSUE TITLE
per_reads/get_freq.py show constant high KNN value through all positions

### ISSUE THREAD

**Issue by hanliaoucla** [novoalab/nanoRMS#8]
Hello,

I have a question about input fast5 file used for per_read modification stoichiometry calculation here:

When I used the fast5 files described below to calculate RNA modification stoichiometry with Tombo, I found that Ctrl vs F2 always had similar KNN values around 0.22 for every positions (even though no modification was found (by other methods from literature) on those positions), while Ctrl vs F1 shown a expected result. 

Ctrl was base-called by guppy4.3.3 during sequencing and then re-called by guppy 4.5.3 later;
F1 was only base-called after sequencing by guppy 4.5.3;
F2 base-calling during sequencing was interrupted and ~85% reads remained raw. Base calling was done later with guppy 4.5.3.

Base calling command was:
~/guppy/bin/guppy_basecaller --input_path ~/Analysis/Nanopore/RawFast5/ --recursive --save_path ~/Analysis/Nanopore/CalledFast5/Test --flowcell FLO-MIN106 --kit SQK-RNA002 --disable_qscore_filtering --fast5_out --device cuda:0

The construction of those fast5 files are:
> h5ls -r Ctrl.fast5 | less
/                        Group
/read_00011303-a051-4af8-8835-3cf4813adbe6 Group
/read_00011303-a051-4af8-8835-3cf4813adbe6/Analyses Group
/read_00011303-a051-4af8-8835-3cf4813adbe6/Analyses/Basecall_1D_000 Group
/read_00011303-a051-4af8-8835-3cf4813adbe6/Analyses/Basecall_1D_000/BaseCalled_template Group
/read_00011303-a051-4af8-8835-3cf4813adbe6/Analyses/Basecall_1D_000/BaseCalled_template/Fastq Dataset {SCALAR}
/read_00011303-a051-4af8-8835-3cf4813adbe6/Analyses/Basecall_1D_000/Summary Group
/read_00011303-a051-4af8-8835-3cf4813adbe6/Analyses/Basecall_1D_000/Summary/basecall_1d_template Group
/read_00011303-a051-4af8-8835-3cf4813adbe6/Analyses/Basecall_1D_001 Group
/read_00011303-a051-4af8-8835-3cf4813adbe6/Analyses/Basecall_1D_001/BaseCalled_template Group
/read_00011303-a051-4af8-8835-3cf4813adbe6/Analyses/Basecall_1D_001/BaseCalled_template/Fastq Dataset {SCALAR}
/read_00011303-a051-4af8-8835-3cf4813adbe6/Analyses/Basecall_1D_001/BaseCalled_template/Move Dataset {14502}
/read_00011303-a051-4af8-8835-3cf4813adbe6/Analyses/Basecall_1D_001/BaseCalled_template/Trace Dataset {14502, 8}
/read_00011303-a051-4af8-8835-3cf4813adbe6/Analyses/Basecall_1D_001/Summary Group
/read_00011303-a051-4af8-8835-3cf4813adbe6/Analyses/Basecall_1D_001/Summary/basecall_1d_template Group
/read_00011303-a051-4af8-8835-3cf4813adbe6/Analyses/Segmentation_000 Group
/read_00011303-a051-4af8-8835-3cf4813adbe6/Analyses/Segmentation_000/Summary Group
/read_00011303-a051-4af8-8835-3cf4813adbe6/Analyses/Segmentation_000/Summary/segmentation Group
/read_00011303-a051-4af8-8835-3cf4813adbe6/Analyses/Segmentation_001 Group
/read_00011303-a051-4af8-8835-3cf4813adbe6/Analyses/Segmentation_001/Summary Group
/read_00011303-a051-4af8-8835-3cf4813adbe6/Analyses/Segmentation_001/Summary/segmentation Group
/read_00011303-a051-4af8-8835-3cf4813adbe6/Raw Group
/read_00011303-a051-4af8-8835-3cf4813adbe6/Raw/Signal Dataset {157561/Inf}
/read_00011303-a051-4af8-8835-3cf4813adbe6/channel_id Group
/read_00011303-a051-4af8-8835-3cf4813adbe6/context_tags Group
/read_00011303-a051-4af8-8835-3cf4813adbe6/tracking_id Group

> h5ls -r F1.fast5 | less
/                        Group
/read_00012b00-01f5-49c6-a44e-c6d27ea4623e Group
/read_00012b00-01f5-49c6-a44e-c6d27ea4623e/Analyses Group
/read_00012b00-01f5-49c6-a44e-c6d27ea4623e/Analyses/Basecall_1D_000 Group
/read_00012b00-01f5-49c6-a44e-c6d27ea4623e/Analyses/Basecall_1D_000/BaseCalled_template Group
/read_00012b00-01f5-49c6-a44e-c6d27ea4623e/Analyses/Basecall_1D_000/BaseCalled_template/Fastq Dataset {SCALAR}
/read_00012b00-01f5-49c6-a44e-c6d27ea4623e/Analyses/Basecall_1D_000/BaseCalled_template/Move Dataset {9154}
/read_00012b00-01f5-49c6-a44e-c6d27ea4623e/Analyses/Basecall_1D_000/BaseCalled_template/Trace Dataset {9154, 8}
/read_00012b00-01f5-49c6-a44e-c6d27ea4623e/Analyses/Basecall_1D_000/Summary Group
/read_00012b00-01f5-49c6-a44e-c6d27ea4623e/Analyses/Basecall_1D_000/Summary/basecall_1d_template Group
/read_00012b00-01f5-49c6-a44e-c6d27ea4623e/Analyses/Segmentation_000 Group
/read_00012b00-01f5-49c6-a44e-c6d27ea4623e/Analyses/Segmentation_000/Summary Group
/read_00012b00-01f5-49c6-a44e-c6d27ea4623e/Analyses/Segmentation_000/Summary/segmentation Group
/read_00012b00-01f5-49c6-a44e-c6d27ea4623e/Raw Group
/read_00012b00-01f5-49c6-a44e-c6d27ea4623e/Raw/Signal Dataset {100850/Inf}
/read_00012b00-01f5-49c6-a44e-c6d27ea4623e/channel_id Group
/read_00012b00-01f5-49c6-a44e-c6d27ea4623e/context_tags Group
/read_00012b00-01f5-49c6-a44e-c6d27ea4623e/tracking_id Group

>  h5ls -r F2.fast5 | less
/                        Group
/read_0026764a-0da0-463d-822c-bfc44adfb79c Group
/read_0026764a-0da0-463d-822c-bfc44adfb79c/Analyses Group
/read_0026764a-0da0-463d-822c-bfc44adfb79c/Analyses/Basecall_1D_000 Group
/read_0026764a-0da0-463d-822c-bfc44adfb79c/Analyses/Basecall_1D_000/Summary Group
/read_0026764a-0da0-463d-822c-bfc44adfb79c/Analyses/Basecall_1D_001 Group
/read_0026764a-0da0-463d-822c-bfc44adfb79c/Analyses/Basecall_1D_001/BaseCalled_template Group
/read_0026764a-0da0-463d-822c-bfc44adfb79c/Analyses/Basecall_1D_001/BaseCalled_template/Fastq Dataset {SCALAR}
/read_0026764a-0da0-463d-822c-bfc44adfb79c/Analyses/Basecall_1D_001/BaseCalled_template/Move Dataset {13850}
/read_0026764a-0da0-463d-822c-bfc44adfb79c/Analyses/Basecall_1D_001/BaseCalled_template/Trace Dataset {13850, 8}
/read_0026764a-0da0-463d-822c-bfc44adfb79c/Analyses/Basecall_1D_001/Summary Group
/read_0026764a-0da0-463d-822c-bfc44adfb79c/Analyses/Basecall_1D_001/Summary/basecall_1d_template Group
/read_0026764a-0da0-463d-822c-bfc44adfb79c/Analyses/Segmentation_000 Group
/read_0026764a-0da0-463d-822c-bfc44adfb79c/Analyses/Segmentation_000/Summary Group
/read_0026764a-0da0-463d-822c-bfc44adfb79c/Analyses/Segmentation_001 Group
/read_0026764a-0da0-463d-822c-bfc44adfb79c/Analyses/Segmentation_001/Summary Group
/read_0026764a-0da0-463d-822c-bfc44adfb79c/Analyses/Segmentation_001/Summary/segmentation Group
/read_0026764a-0da0-463d-822c-bfc44adfb79c/Raw Group
/read_0026764a-0da0-463d-822c-bfc44adfb79c/Raw/Signal Dataset {144915/Inf}
/read_0026764a-0da0-463d-822c-bfc44adfb79c/channel_id Group
/read_0026764a-0da0-463d-822c-bfc44adfb79c/context_tags Group
/read_0026764a-0da0-463d-822c-bfc44adfb79c/tracking_id Group

All the rest analysis (get_features and get_freq) were following ReadMe instruction.

Anyone knows how can I solve this problem?

Thanks in advance!

**Comment by enovoa** [comment]
Hi @hanliaoucla , I will leave @lpryszcz to reply with further detail, but if I understand correctly from your commands above, you are feeding ALL positions to NanoRMS RNA modification prediction steps. Please note that as stated in the GitHub NanoRMS documentation, the recommended pipeline is to predict RNA modified sites with a different software (e.g. we use an EpiNano wrapper in the repository),  and then use NanoRMS to predict RNA modification stoichiometry in the list of "RNA-modified sites".  NanoRMS will always try to find two populations in your reads, so it should be used with "predicted RNA modified sites" rather than all sites. Otherwise it will predict a "background" modification level for all positions. Also of note, we recommend to use the difference in modification rather than the absolute modification levels. Please let us know if this clarifies your question.

**Comment by hanliaoucla** [comment]
Hi Dr. Novoa, @enovoa, thanks for your reply. 

At beginning, we just used predicted/confirmed 2-O-Me sites on RNA to look at difference in modification between control and two other samples. Later, we found that all those position showed similar difference on KNN for control and F2 which seems impossible biologically. Therefore, we checked difference of KNN on unmodified sites (Ctrl vs F1) and also all those unmodified positions showed the same result as modified sites. I think those weird data might be resulted from different basecalling methods of my input Fast5 files (as mentioned above).

**Comment by lpryszcz** [comment]
Hi @hanliaoucla , 
```
Ctrl was base-called by guppy4.3.3 during sequencing and then re-called by guppy 4.5.3 later;
F1 was only base-called after sequencing by guppy 4.5.3;
F2 base-calling during sequencing was interrupted and ~85% reads remained raw. Base calling was done later with guppy 4.5.3.
```
It's clearly a problem with re-basecalling. This behavior though is peculiar because `get_features.py` should always select the results from the latest basecalling (relevant code below)
```python
    # trace and move data from read
    bcgrp = read.get_latest_analysis("Basecall_1D")
    trace = read.get_analysis_dataset(bcgrp, "BaseCalled_template/Trace")
    move = read.get_analysis_dataset(bcgrp, "BaseCalled_template/Move")
    move_pos = np.append(np.argwhere(move==1).flatten(), len(trace)) # add end of trace
```
So the problem similar to what you described could indeed happen, but only if the second basecalling (v4.5.3) for F2 didn't completed for some subset of reads. In this case, `get_features.py` would pickup v4.5.3 for those reads that completed second basecalling and v4.3.3 for the reads that didn't completed basecalling with v4.5.3.  But, if v4.5.3 correctly basecalled all reads, then only this basecalling result should be selected by `get_features.py`. 

Are you certain all F2 reads are correctly basecalled with v4.5.3?  
You can check ie using below pipe the exact number of reads basecalled by each run. 
```
h5ls -r F2.fast5 | grep Fastq | cut -f4 -d'/'|sort|uniq -c
```

What I'd recommend at this point is to revert F2 reads to raw fast5 and basecall them again using only v4.5.3. 
Reverting (removing all additional analyses) can be achieved ie using `compress_fast5` from [ont_fast5_api](https://github.com/nanoporetech/ont_fast5_api/)
```bash
compress_fast5 --sanitize -c vbz -i in_fast5_dir -s out_fast5_dir
```
